### ISSUE TITLE
Convert content from multiple formats to Turtle

### ISSUE THREAD

**Issue by sebastienhenau** [oSoc15/dcat-validator#10]
When a user uploads a file and it's in a XML format, I have to use a javascript library to convert the XML to Turtle. I first have to parse the data and then serialize it in order to do the conversion.

**Comment by coreation** [comment]
@sebastienhenau any update on what library you're going to use?

**Comment by sebastienhenau** [comment]
The library I use is RDF-Ext, which has multiple parsers and serializers

**Comment by coreation** [comment]
Great, you should link them somewhere in the validator page. So something like "supports json-ld, turtle, n3" and so on. Also it will be alot easier for you if they have to specify which type of format they're giving you, so that you only need to make a switch (or if-else) statement to know how to serialise the content.
