### ISSUE TITLE
RDFa formatter

### ISSUE THREAD

**Issue by pietercolpaert** [oSoc15/dcat-validator#25]
At http://dcat.be, in the tools and resources section, we also tell people that they can use RDFa to create DCAT feeds. Could we find an RDFa parser as well for when an html file is given instead?

**Comment by sebastienhenau** [comment]
In the library we use to parse JSON-LD, XML and Turtle there is another parser I found called rdf.parseRdfa and rdf.parseHtml. Maybe I could use one of these parsers when a html file is given.

**Comment by pietercolpaert** [comment]
What's the status of this? We might need it for a project at the Flemish government :)

**Comment by sebastienhenau** [comment]
I will start working on this today

**Comment by sebastienhenau** [comment]
The library RDF-Ext can't parse an RDFa format.

**Comment by sebastienhenau** [comment]
## Formats
This validator uses a library called RDF-Ext which contains different parsers and serializers. For the validator this library is used to parse RDF:XML, JSON-LD and Turtle and then serialize it to Turtle so it can be read by the validation library, because this library online reads Turtle.

## ParseRdfa
In the RDF-Ext library, there is a function called parseRdfa which can be used to parse the RDFa. After testing this the parser returns different errors that are located in the library RDF-Ext. Because of this there is no possibility to parse RDFa, using this library.

## The issue
The issue is that the user selects a format and when this is RDFa, the user can then parse his RDFa and it gets serialized to Turtle so it can be validated. The user can manually insert the RDFa format, he can select it and upload it or he can do this by inserting the URI. The user can also, instead of selecting a format when inserting a URI, select Automatic which will detect what content-Type the file is and then based on this select it parser so it can be serialised.

All these features are already in the script.js file and work for the formats RDF:XML, JSON-LD and Turtle. The only thing that I can think of that has to be done to make the RDFa parsing work is to maybe use and implement a different library which parses the RDFa and serializes it or can be serialized by the library RDF-Ext. Then this result can be send as an argument to the validation library which will validate the data serialized to Turtle.

**Comment by pietercolpaert** [comment]
To be fixed in issue #29
